version: '3'

services:
  dbs:
    image: cassandra:latest
#    command: ["/bin/sh", "-c", "service mysql start && while true; do sleep 3600; done"]
    container_name: dbs-1
    networks:
      my_network:
        ipv4_address: 172.18.0.2
    ports:
      - "9042:9042"

  serv:
    image: pratham17/apps:v6
    container_name: app-1
    networks:
      my_network:
        ipv4_address: 172.18.0.3
    depends_on:
      - dbs
    entrypoint: /root/entrypoint.sh
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"

  ngin:
    image: pratham17/nginx:v2
    container_name: face-1
    networks:
      my_network:
        ipv4_address: 172.18.0.4
    depends_on:
      - serv
    ports:
      - "801:80"

networks:
  my_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
